name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Pranava-Pai-N
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan output
          git add -f dist/snake.svg
          git commit -m "Generate snake animation"
          git push -f https://x-access-token:${{ secrets.GH_PAT }}@github.com/Pranava-Pai-N/Pranava-Pai-N.git output
